### ISSUE TITLE
mapReduce & keys support

### ISSUE THREAD

**Issue by ghost** [mranney/node_riak#12]
Hi There!

You saved my hide! Other libraries of riak weren't working fine on stress operations, such as saving a thousand keys and the such.

I had to design functions to support `mapReduce` and get all the `keys`(don't ask why :D); So, question:

Do you mind if I fork this module and publish my own module with these two functions (with the due credit and the comment: "I had to fork this one, blah blah blah"). Or do I make a PR of these two functions here?

Thanks a lot!

**Comment by DTrejo** [comment]
I'd say do both, as it might be a bit before they are merged.
If you do send in a PR, please include docs and maybe also add a test for each one?
Cheers,
D

**Comment by ghost** [comment]
Closing. Never did that code. Sorry.
