### ISSUE TITLE
Example for .post -method

### ISSUE THREAD

**Issue by jockster** [mranney/node_riak#9]
Is it possible to see an example on how the `post`-method would be used?

Thanks

**Comment by DTrejo** [comment]
Check out the tests?

**Comment by jockster** [comment]
Did so already but couldn't find anything unfortunately.

**Comment by DTrejo** [comment]
If you'd like to read the code and write some docs, that would be appreciated.

**Comment by jockster** [comment]
Please check out the pull request.

**Comment by jockster** [comment]
Anything?

**Comment by DTrejo** [comment]
Taking a look at #10 now :)

Cheers,
D
